# Generated by Django 4.2.2 on 2023-06-16 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samsApp.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samsApp.student')),
            ],
        ),
    ]
