# Generated by Django 4.2.2 on 2023-06-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samsApp', '0002_snotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.CharField(default='B1', max_length=50),
        ),
    ]
